### ISSUE TITLE
vignette review

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/quitte#18]
> We have collected a list of minor recommendation for changes but none of these are important:
> 
> 1. Move loading of exemplary data further up and make it more clear how to read in exemplary data from quitte (i.e. write "data <- quitte_example_data")
>  2. Always put explanation in front of code for function, e.g.
>    - inline.data.frame()
>    - order.levels()
> 3. Add explanation „By settting only.new = TRUE“ to the text „It is also possible to only keep the newly calculated values for further manipulation.“
> 4. Format the line „(Note: You don't have to call the mip-functions via the double colon (::) operator. This is only needed in this vignette, since quitte can't import mip.)“ as a Tip
> 
> One thing we noticed for the interpolation, is that the results are same for linear and spline interpolation. Is this how it is supposed to be?

**Comment by rkrekeler** [comment]
I had a hard time tracing a bug in my code, because I misinterpreted documentation of `calc_addVariable` / `calc_addVariable_`. I understood that if the argument `completeMissing == TRUE` the function would just replace implicitly missing data combinations with zero in the internal calculation. What really happens is that the formerly missing data combination with value zero are also added as rows to the output. If this is intended I think the documentation could be clearer here. Eg...

> ... missing combinations of data are added to the data with 0 before calculation.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> I had a hard time tracing a bug in my code, because I misinterpreted documentation of `calc_addVariable` / `calc_addVariable_`. I understood that if the argument `completeMissing == TRUE` the function would just replace implicitly missing data combinations with zero in the internal calculation. What really happens is that the formerly missing data combination with value zero are also added as rows to the output. If this is intended I think the documentation could be clearer here. Eg...
> 
> > ... missing combinations of data are added to the data with 0 before calculation.

Done. 14064ae

**Comment by rkrekeler** [comment]
Cool, thank you!
